- build.rs
- cstrml/staking/src/inflation.rs
- cstrml/staking/src/lib.rs
- cstrml/staking/src/migration.rs
- cstrml/staking/src/mock.rs
- cstrml/staking/src/slashing.rs
- cstrml/staking/src/tests.rs
- cstrml/tee/src/api.rs
- cstrml/tee/src/lib.rs
- cstrml/tee/src/mock.rs
- cstrml/tee/src/tests.rs
- primitives/src/constants.rs
- primitives/src/lib.rs
- runtime/build.rs
- runtime/src/lib.rs
- src/chain_spec.rs
- src/cli.rs
- src/main.rs
- src/service.rs
> Format code

- cstrml/staking/src/lib.rs
- cstrml/staking/src/tests.rs
- runtime/src/lib.rs
> change stake limit update logic in the era end

- cstrml/staking/src/lib.rs
> [Hotfix] Fix zero-stake validator not be removed

- cstrml/staking/src/lib.rs
- src/chain_spec.rs
1. breaks `nominate`, `validate` and `bond_extra` api
> [GPoS] Change active check for effective vote

- Cargo.toml
- cstrml/staking/Cargo.toml
- cstrml/staking/src/lib.rs
- cstrml/staking/src/tests.rs
- cstrml/tee/Cargo.toml
- primitives/Cargo.toml
- runtime/Cargo.toml
Fix 2 bugs:
1. guarantor's ledger should clear before `for_each`;
2. removing guarantor strategy is wrong;
> Prepping 0.2.0

- cstrml/staking/src/inflation.rs
- cstrml/staking/src/lib.rs
- cstrml/staking/src/migration.rs
- cstrml/staking/src/mock.rs
- cstrml/staking/src/slashing.rs
- cstrml/staking/src/tests.rs
> [GPoS] Change nominatX to guarantX

- cstrml/staking/src/lib.rs
- Add `chill-validator/guarantor` logic;
- Fix era-end updating logic;
- Fix `guarantee` remain check logic
> Fix voting check on stake limit

- Cargo.toml
- cstrml/staking/Cargo.toml
- cstrml/staking/src/lib.rs
- cstrml/tee/Cargo.toml
- primitives/Cargo.toml
- runtime/Cargo.toml
- src/chain_spec.rs
- Simplify some code logic
- Pepping 0.2.2
> Pepping 0.2.2

- cstrml/staking/src/mock.rs
- cstrml/tee/src/lib.rs
- cstrml/tee/src/mock.rs
- cstrml/tee/src/tests.rs
- src/chain_spec.rs
- Fix overall network workload updated bug;
- Change `last_report_slot` to `current_report_slot`;
> [Hotfix] fix network workload update

- cstrml/staking/src/lib.rs
- cstrml/staking/src/mock.rs
- cstrml/staking/src/tests.rs
- fix one overflow panic
- support mock workload in staking module
- refine some tests of staking module
> Refine some tests of staking module

- cstrml/staking/src/lib.rs
- cstrml/tee/src/lib.rs
- node/src/service.rs
- runtime/src/lib.rs
> refine comments

- cstrml/staking/src/lib.rs
- cstrml/tee/src/lib.rs
> Fix clear stakers

- cstrml/market/src/lib.rs
- cstrml/market/src/mock.rs
- cstrml/market/src/tests.rs
- cstrml/staking/src/lib.rs
- cstrml/tee/src/lib.rs
- cstrml/tee/src/mock.rs
1. Make `files` into `file_map` for tee active check;
2. Expand `MarketInterface`, preparing the interface with tee file check;
> [Market] Change provision

- cstrml/market/src/lib.rs
- cstrml/market/src/mock.rs
- cstrml/market/src/tests.rs
- cstrml/tee/src/lib.rs
- cstrml/tee/src/mock.rs
- cstrml/tee/src/tests.rs
- runtime/src/lib.rs
almost 100% random, it uses `RandomnessCollectiveFlip` as random order id generator
> [Market] Solve random order id

- .github/workflows/rust.yml
- Cargo.lock
- cstrml/balances/Cargo.toml
- cstrml/balances/src/benchmarking.rs
- cstrml/balances/src/lib.rs
- cstrml/balances/src/tests.rs
- cstrml/balances/src/tests_composite.rs
- cstrml/balances/src/tests_local.rs
- cstrml/staking/Cargo.toml
- cstrml/staking/src/mock.rs
- runtime/Cargo.toml
The version of this balance is alpha 6 tag 1
> [Market] Folk balances into our repo and replace pallet balances to balances in runtime and staking

- cstrml/market/src/lib.rs
- cstrml/market/src/mock.rs
- cstrml/market/src/tests.rs
- cstrml/payment/src/lib.rs
- cstrml/payment/src/mock.rs
- cstrml/payment/src/tests.rs
- cstrml/staking/src/mock.rs
- cstrml/tee/src/lib.rs
- cstrml/tee/src/mock.rs
- cstrml/tee/src/tests.rs
- runtime/src/lib.rs
1. Add amount into `StorageOrder`;
2. Re-design the `Payment` trait for better payment logic;
3. Merge `on_sorder_success` and `maybe_set_sorder` function;
4. Simplify `slot_pay `;
5. Fix `start_delayed_pay` inside `tee` module(Only call this function when file first been confirmed);
6. Refine some *variable naming* and *comments*;
> [Payment] Refactoring code structure and fix start delayed pay bug

- cstrml/market/src/lib.rs
- cstrml/market/src/tests.rs
- cstrml/tee/src/lib.rs
- cstrml/tee/src/mock.rs
- cstrml/tee/src/tests.rs
- Fixed #150 
- Fix register after been a provider
> [Market] Fix duplicate file and register again

- cstrml/market/src/lib.rs
- cstrml/market/src/tests.rs
> [Market] Support cut_pledge without register

- cstrml/market/src/lib.rs
- cstrml/market/src/tests.rs
> [Market] Add check for the same provider and client

- cstrml/market/src/lib.rs
- cstrml/market/src/tests.rs
> [Market] Remove the lock when total and used are set to zero

- .github/workflows/rust.yml
- Cargo.lock
- cstrml/balances/Cargo.toml
- cstrml/balances/src/benchmarking.rs
- cstrml/balances/src/lib.rs
- cstrml/balances/src/tests.rs
- cstrml/balances/src/tests_composite.rs
- cstrml/balances/src/tests_local.rs
- cstrml/market/Cargo.toml
- cstrml/market/src/lib.rs
- cstrml/market/src/tests.rs
- cstrml/payment/Cargo.toml
- cstrml/staking/Cargo.toml
- cstrml/staking/src/lib.rs
- cstrml/tee/Cargo.toml
- primitives/Cargo.toml
- primitives/src/lib.rs
- primitives/src/traits.rs
- runtime/Cargo.toml
> [Market+GPoS+Balance] Add transferrable_balance into balance module

- cstrml/staking/src/lib.rs
- cstrml/tee/src/lib.rs
- Add `set_code`
- Add comment {`<weight>`} measuring *TC and DBTry*
> [MPoW] Add set enclave code

- cstrml/payment/src/lib.rs
- cstrml/payment/src/mock.rs
- runtime/src/lib.rs
Fix #159. Checking #174 with @BOBOKaa
> [Payment] Replace force transfer with currency's transfer

- cstrml/market/src/lib.rs
- cstrml/market/src/mock.rs
- cstrml/market/src/tests.rs
- cstrml/payment/src/mock.rs
- cstrml/tee/src/lib.rs
- cstrml/tee/src/mock.rs
- runtime/src/lib.rs
> [Market] Add market punishing mechanism

- cstrml/market/src/mock.rs
- cstrml/payment/src/mock.rs
- cstrml/staking/src/mock.rs
- cstrml/tee/src/lib.rs
- cstrml/tee/src/mock.rs
- cstrml/tee/src/tests.rs
- node/src/chain_spec.rs
1. Rename `TeeIdentity` to `Identity`;
2. Add `code` into `Identity`;
3. Add new store `ABExpire`(recording the AB Upgrade expired block);
4. Add new test for AB Upgrade;
> [MPoW] Add AB Upgrade 

- Cargo.lock
- cstrml/market/src/lib.rs
- cstrml/payment/Cargo.toml
- cstrml/payment/src/lib.rs
- cstrml/payment/src/mock.rs
- cstrml/payment/src/tests.rs
- cstrml/tee/src/lib.rs
- runtime/src/lib.rs
Fix #158 
Fix #153(Need check the menchanism)
- Remove schedular and use `on_initialize`
- Add new storage to stora slot pay
- Add regular batch transfer functionality
- Remove Clients
- Rename Payments and Ledger back to PaymentLedger
> [Payment] New slot pay menchanism

- cstrml/tee/src/lib.rs
- cstrml/tee/src/tests.rs
1. Solve 1 FIXME
2. Add tests including:
- Happy pass
- Merged work report(reserved, files)
- Not upgrade
- Replay attack
- Shrink attack
> [MPoW] Add AB Upgrade tests

- cstrml/staking/src/lib.rs
- docker/README.md
- Separate `Reward::event` into `authoring_reward` and `staking_reward`.
- Improve some docker `README`
> [GPoS] Improve reward event

- Cargo.lock
- cstrml/balances/Cargo.toml
- cstrml/market/Cargo.toml
- cstrml/payment/Cargo.toml
- cstrml/staking/Cargo.toml
- cstrml/tee/Cargo.toml
- node/Cargo.toml
- primitives/Cargo.toml
- runtime/Cargo.toml
- runtime/src/impls.rs
- runtime/src/lib.rs
- Prepping `0.6.1`
- Optimize crust runtime
> Optimize crust runtime construction

- cstrml/market/src/lib.rs
- cstrml/staking/src/lib.rs
- cstrml/tee/src/lib.rs
- runtime/src/lib.rs
- Change all `balances`, `market`, `staking` and `tee`'s extrinsic weight;
- Change Payment release `Frequency` to `10 * MINUTES`
> [Params] Change maxwell on-chain params

- cstrml/staking/src/lib.rs
- cstrml/staking/src/mock.rs
- cstrml/staking/src/tests.rs
> [GPoS] New Reward Mechanism

- cstrml/staking/src/lib.rs
- cstrml/staking/src/tests.rs
Fixed #245 
- Change test `topdown_should_not_overflow_validators`
- Add 1 test `reward_with_no_stake_limit `
> [GPoS] Remove active check

- cstrml/market/src/lib.rs
- cstrml/market/src/tests.rs
- cstrml/payment/src/tests.rs
- primitives/src/lib.rs
Fix #222
add a file_path for each sorder
support renaming the file path later
> [Market] Support directory

- Cargo.lock
- Cargo.toml
- cstrml/balances/Cargo.toml
- cstrml/market/Cargo.toml
- cstrml/payment/Cargo.toml
- cstrml/staking/Cargo.toml
- cstrml/swork/Cargo.toml
- node/Cargo.toml
- node/src/command.rs
- node/src/service.rs
- primitives/Cargo.toml
- rpc/Cargo.toml
- rpc/src/lib.rs
- runtime/Cargo.toml
- runtime/src/lib.rs
> [Upgrade] Upgrade into rc6

- cstrml/staking/src/lib.rs
- cstrml/staking/src/mock.rs
- cstrml/staking/src/tests.rs
- runtime/src/lib.rs
Impact:
Several tests are fixed.
> [GPoS] Support active era

- cstrml/swork/src/lib.rs
- cstrml/swork/src/mock.rs
- cstrml/swork/src/tests.rs
> [MPoW] Fix A/B upgrade

- Cargo.lock
- cstrml/market/src/mock.rs
- cstrml/staking/Cargo.toml
- cstrml/staking/src/mock.rs
- cstrml/swork/src/lib.rs
- cstrml/swork/src/mock.rs
- cstrml/swork/src/tests.rs
- runtime/src/lib.rs
> [MPoW] Add maximum bonds restriction

- cstrml/swork/src/lib.rs
- cstrml/swork/src/mock.rs
- cstrml/swork/src/tests.rs
> [MPoW] Fix files transfer check bug

- cstrml/swork/src/api.rs
- cstrml/swork/src/lib.rs
- cstrml/swork/src/utils.rs
Stage 1 of #176. Move encoding and constructing WR to on-chain first
> [MPoW] Onchain Crypto stage I

- cstrml/swork/src/lib.rs
- cstrml/swork/src/tests.rs
> [MPoW] Extend IdBonds limitation during upgrading process

- cstrml/market/src/benchmarking.rs
- cstrml/market/src/lib.rs
- cstrml/market/src/mock.rs
- cstrml/market/src/weight.rs
- cstrml/swork/src/mock.rs
- runtime/src/lib.rs
> [Benchmarking] Adopt new weight system for market

- cstrml/market/src/lib.rs
- cstrml/market/src/mock.rs
- cstrml/staking/src/benchmarking.rs
- cstrml/staking/src/lib.rs
- cstrml/staking/src/mock.rs
- cstrml/staking/src/weight.rs
- cstrml/swork/src/benchmarking.rs
- cstrml/swork/src/lib.rs
- cstrml/swork/src/mock.rs
- cstrml/swork/src/weight.rs
- runtime/src/lib.rs
> [Benchmarking] New weight system for swork and staking

- cstrml/swork/src/lib.rs
> [MPoW] add new event in upgrade extrinsic

- Cargo.lock
- node/src/chain_spec.rs
- runtime/Cargo.toml
- runtime/src/lib.rs
> [Democracy] Support democracy

- Cargo.lock
- cstrml/candy/Cargo.toml
- cstrml/candy/src/lib.rs
Fix #303 
- Need cherry-pick to release/0.10.0
> [Candy] Support bonding ETH address

- cstrml/staking/src/lib.rs
- cstrml/staking/src/tests.rs
> [GPoS] Remove random selection

- cstrml/swork/src/lib.rs
- cstrml/swork/src/tests.rs
> [MPoW] Transfer A's report in slot to B during AB upgrade process

- cstrml/staking/src/lib.rs
- cstrml/staking/src/tests.rs
> [GPoS] Remove stake limit when chill account

- Cargo.lock
- cstrml/balances/Cargo.toml
- cstrml/candy/Cargo.toml
- cstrml/market/Cargo.toml
- cstrml/staking/Cargo.toml
- cstrml/swork/Cargo.toml
- node/Cargo.toml
- primitives/Cargo.toml
- rpc/Cargo.toml
- runtime/Cargo.toml
Involved with newest substrate and DSM 2.0
> Prepping 0.11.0

- cstrml/staking/src/benchmarking.rs
- cstrml/staking/src/lib.rs
- cstrml/staking/src/tests.rs
- runtime/src/lib.rs
> [GPoS] Support choosing another account as the payee destination

- Cargo.lock
- cstrml/market/Cargo.toml
- cstrml/market/src/lib.rs
- cstrml/market/src/mock.rs
- cstrml/market/src/tests.rs
- cstrml/swork/Cargo.toml
- cstrml/swork/src/lib.rs
- cstrml/swork/src/mock.rs
- cstrml/swork/src/tests.rs
- primitives/src/traits.rs
- runtime/src/lib.rs
> [Market] Refractor some variables and functions

- cstrml/market/src/lib.rs
- cstrml/market/src/mock.rs
- cstrml/market/src/tests.rs
- cstrml/swork/benchmarking/src/mock.rs
- cstrml/swork/src/mock.rs
- runtime/src/lib.rs
> [DSM] Collect 10% tax into reserved pot

- cstrml/staking/src/lib.rs
- cstrml/staking/src/mock.rs
- cstrml/staking/src/tests.rs
- runtime/src/lib.rs
> [GPoS] Staking pot in GPoS for authoring reward and staking reward

- cstrml/market/src/benchmarking.rs
- cstrml/market/src/lib.rs
- cstrml/market/src/mock.rs
- runtime/src/lib.rs
> [DSM] Bring benchmarking back for market

- cstrml/swork/src/lib.rs
Fix #400 
All fee would be removed.
> [MPoW] Remove extrinsic fee of report_works

- cstrml/market/src/lib.rs
- cstrml/market/src/tests.rs
- cstrml/staking/src/lib.rs
- cstrml/staking/src/mock.rs
- cstrml/staking/src/tests.rs
- cstrml/swork/src/lib.rs
- node/src/main.rs
- primitives/src/traits.rs
- runtime/src/lib.rs
> [GPoS + DSM] New storage staking pot reward mechanism

- cstrml/market/src/lib.rs
- cstrml/market/src/mock.rs
- cstrml/market/src/tests.rs
- cstrml/staking/src/mock.rs
- cstrml/swork/src/lib.rs
- cstrml/swork/src/mock.rs
- cstrml/swork/src/tests.rs
- primitives/src/traits.rs
> [MPoW + DSM] Correct file size with reported file size

- cstrml/market/src/lib.rs
- cstrml/market/src/tests.rs
- cstrml/swork/src/mock.rs
> [Market] Inherit file status when place storage order

- cstrml/market/src/lib.rs
> [MPoW] Use binary search instead

- cstrml/market/src/mock.rs
- cstrml/staking/src/mock.rs
- cstrml/swork/benchmarking/src/mock.rs
- cstrml/swork/src/lib.rs
- cstrml/swork/src/mock.rs
- cstrml/swork/src/tests.rs
- runtime/src/lib.rs
> [MPoW] Add punishment for report works failure

- cstrml/market/src/benchmarking.rs
- cstrml/market/src/lib.rs
- cstrml/market/src/tests.rs
- cstrml/swork/benchmarking/src/lib.rs
- cstrml/swork/src/mock.rs
- cstrml/swork/src/tests.rs
> [DSM] Fix the bug if we decrease the reported_replicas_count twice

- cstrml/market/src/mock.rs
- cstrml/staking/src/mock.rs
- cstrml/swork/src/lib.rs
- cstrml/swork/src/mock.rs
- cstrml/swork/src/tests.rs
> [MPoW] Refine punishment mechanism and avoid double mining

- cstrml/swork/src/tests.rs
Please merge it in the last one
> [MPoW] Refine test

- cstrml/staking/src/lib.rs
- cstrml/staking/src/mock.rs
- cstrml/staking/src/tests.rs
- primitives/src/constants.rs
> [GPoS] Switch to Crust Maxwell reward plan

- cstrml/market/src/lib.rs
- cstrml/market/src/tests.rs
- cstrml/staking/src/mock.rs
- cstrml/swork/src/lib.rs
- cstrml/swork/src/tests.rs
- primitives/src/traits.rs
> [DSM] delete_replicas won't call calculate_payout anymore

- cstrml/market/src/tests.rs
- cstrml/swork/src/lib.rs
- cstrml/swork/src/tests.rs
> [DSM] get_total_capacity() is free() + reported_files_size() now

- cstrml/market/src/lib.rs
- cstrml/market/src/tests.rs
- runtime/src/lib.rs
> [DSM] Change param for maxwell and 10x pledge

- cstrml/swork/benchmarking/src/lib.rs
- cstrml/swork/src/lib.rs
- cstrml/swork/src/weight.rs
> [MPoW] Dynamic weight for report works

- cstrml/market/src/mock.rs
- cstrml/staking/src/mock.rs
- cstrml/swork/benchmarking/src/mock.rs
- cstrml/swork/src/lib.rs
- cstrml/swork/src/mock.rs
- cstrml/swork/src/tests.rs
- cstrml/swork/src/weight.rs
- runtime/src/lib.rs
> [MPoW] Support quitting a group and kicking someone out of a group

- cstrml/balances/src/lib.rs
- cstrml/staking/src/lib.rs
> Revert "[Upgrade] Remove staking, balances, treasury and demoncracy"

- cstrml/market/src/lib.rs
- cstrml/market/src/tests.rs
> [DSM] Recharge would make it to pending status if replica's length is zero

- cstrml/balances/src/lib.rs
> Revert "[Runtime] Remove staking, election and balance's lock storage"

- cstrml/staking/src/lib.rs
- cstrml/staking/src/mock.rs
- cstrml/staking/src/tests.rs
- cstrml/swork/benchmarking/src/mock.rs
- cstrml/swork/src/lib.rs
- cstrml/swork/src/mock.rs
Fix that 0 group member(had member before) bug
> [GPoS] Update stake limit according to validators 

- cstrml/market/src/lib.rs
- cstrml/market/src/tests.rs
> [DSM] New file would clear same file in trash

- node/src/chain_spec.rs
- runtime/src/lib.rs
> [Node] Add market module into chain_spec

- cstrml/market/src/benchmarking.rs
- cstrml/market/src/lib.rs
- cstrml/market/src/tests.rs
- cstrml/market/src/weight.rs
- cstrml/staking/src/lib.rs
- cstrml/swork/src/tests.rs
Fix #420 
Fix #421 
Refine `KeepAlive` and `AllowDeath`
> [DSM] Add liquidator mechanism

- cstrml/market/src/lib.rs
- cstrml/market/src/mock.rs
- cstrml/staking/src/lib.rs
- cstrml/swork/benchmarking/src/mock.rs
- cstrml/swork/src/lib.rs
- cstrml/swork/src/mock.rs
- runtime/src/lib.rs
> [DSM + MPoW] Add const parameter

- cstrml/staking/src/lib.rs
- cstrml/staking/src/mock.rs
- cstrml/staking/src/tests.rs
- runtime/src/lib.rs
> [GPoS] Market pot should reward authoring as well

- cstrml/market/src/lib.rs
- cstrml/market/src/mock.rs
- cstrml/market/src/tests.rs
- cstrml/swork/benchmarking/src/mock.rs
- cstrml/swork/src/mock.rs
- runtime/src/lib.rs
> [DSM] Add MaxFileSize Limitation

- cstrml/staking/src/lib.rs
- cstrml/staking/src/tests.rs
> [GPoS] Authoring reward would also be payed to guarantors

- cstrml/market/src/lib.rs
- cstrml/market/src/mock.rs
- cstrml/market/src/tests.rs
- cstrml/staking/src/mock.rs
- cstrml/swork/src/lib.rs
- primitives/src/traits.rs
Storage Migration
1. Calculate a new files_size during the on_runtime_upgrade
Fix #476
> [DSM] files_size is updated by reported_group_count

- cstrml/market/src/lib.rs
- cstrml/market/src/mock.rs
- cstrml/market/src/tests.rs
> [DSM] Only file owner can get storage reward

- cstrml/market/src/lib.rs
Including into `release/0.11.1`(ver: `13`)
Fix #495
> [Market] Optimize some events

- cstrml/market/src/lib.rs
- cstrml/market/src/tests.rs
- cstrml/swork/src/lib.rs
- cstrml/swork/src/tests.rs
> [MPoW] Remove useless ReportedInSlot and fix a bug

- cstrml/market/src/benchmarking.rs
- cstrml/market/src/lib.rs
- cstrml/market/src/mock.rs
- cstrml/market/src/tests.rs
- cstrml/swork/benchmarking/src/lib.rs
- cstrml/swork/benchmarking/src/mock.rs
- cstrml/swork/src/mock.rs
- cstrml/swork/src/tests.rs
- runtime/src/lib.rs
> [DSM] Remove expected_replica_count

- runtime/src/lib.rs
> [DSM] Change UsedTrashMaxSize to 1000

- cstrml/market/src/benchmarking.rs
- cstrml/market/src/lib.rs
- cstrml/market/src/mock.rs
- cstrml/market/src/tests.rs
- cstrml/swork/benchmarking/src/lib.rs
- cstrml/swork/benchmarking/src/mock.rs
- cstrml/swork/src/mock.rs
- cstrml/swork/src/tests.rs
- runtime/src/lib.rs
> [DSM] Support pre paid and renew mechanism

- cstrml/market/src/benchmarking.rs
- cstrml/market/src/lib.rs
- cstrml/market/src/tests.rs
- cstrml/market/src/weight.rs
- cstrml/swork/benchmarking/src/lib.rs
- cstrml/swork/src/mock.rs
- cstrml/swork/src/tests.rs
> [Market] Rename claimed at to calculated at

- cstrml/balances/src/lib.rs
- cstrml/balances/src/tests.rs
- cstrml/market/src/lib.rs
- cstrml/staking/src/lib.rs
- primitives/src/traits.rs
Fix #511 
Cannot remove balance since we have to expose the internal function
> [GPoS + Market] Use usable balance in market and free balance in staking

- cstrml/staking/src/lib.rs
- cstrml/staking/src/tests.rs
> [MPoW] Switch to the stash account to create group and be the owner

- cstrml/market/src/lib.rs
- cstrml/market/src/tests.rs
> [Market] Return ok when file doesn't exist in calculate_reward

- cstrml/swork/src/lib.rs
- cstrml/swork/src/tests.rs
> [MPoW] Extend punishment if the member offline more than once

- cstrml/staking/src/lib.rs
> [GPoS] Refine event

- node/src/chain_spec.rs
- runtime/src/lib.rs
> [Runtime] Add CSM module

- cstrml/staking/src/lib.rs
- cstrml/staking/src/mock.rs
- cstrml/staking/src/tests.rs
> [GPoS] Support Stage-2 stake limit calculation logic

- cstrml/claims/src/lib.rs
- cstrml/claims/src/tests.rs
- runtime/src/lib.rs
* Add force delete cru18 precclaim and add comments
* Pump spec ver 20
> Add force delete cru18 precclaim (#589)

- Cargo.lock
- Cargo.toml
- cstrml/balances/Cargo.toml
- cstrml/candy/Cargo.toml
- cstrml/claims/Cargo.toml
- cstrml/csm-locking/Cargo.toml
- cstrml/csm-locking/src/lib.rs
- cstrml/csm-locking/src/mock.rs
- cstrml/csm-locking/src/tests.rs
- cstrml/csm-locking/src/weight.rs
- cstrml/market/Cargo.toml
- cstrml/market/src/lib.rs
- cstrml/market/src/mock.rs
- cstrml/market/src/tests.rs
- cstrml/staking/Cargo.toml
- cstrml/staking/src/lib.rs
- cstrml/staking/src/tests.rs
- cstrml/staking/src/weight.rs
- cstrml/swork/Cargo.toml
- cstrml/swork/benchmarking/Cargo.toml
- cstrml/swork/benchmarking/src/mock.rs
- cstrml/swork/src/mock.rs
- node/Cargo.toml
- node/src/chain_spec.rs
- primitives/Cargo.toml
- rpc/Cargo.toml
- runtime/Cargo.toml
- runtime/src/lib.rs
> Maxwell 23

- cstrml/csm-locking/src/lib.rs
- cstrml/market/src/lib.rs
- cstrml/market/src/mock.rs
- cstrml/market/src/tests.rs
- cstrml/market/src/weight.rs
- cstrml/swork/benchmarking/src/mock.rs
- cstrml/swork/src/mock.rs
- runtime/src/lib.rs
1. Free Space Storage
2. CSM related guarantee, cancel guarantee and set perf
3. Independent Liquaity period and set it to 15 Days
> Maxwell 25

- cstrml/market/src/lib.rs
- cstrml/market/src/mock.rs
- cstrml/market/src/tests.rs
Better to use const instead of storage
> [Market] Add limit for groups length and replicas length

- cstrml/market/src/lib.rs
- cstrml/market/src/mock.rs
- cstrml/market/src/tests.rs
- cstrml/swork/benchmarking/src/mock.rs
- cstrml/swork/src/mock.rs
- primitives/src/constants.rs
- runtime/src/lib.rs
>  [Market] Update file price per blocks

- cstrml/staking/src/lib.rs
- cstrml/staking/src/mock.rs
- cstrml/staking/src/tests.rs
- cstrml/staking/src/weight.rs
- primitives/src/constants.rs
1. Remove staking pot
2. 5000000 CRU for the first year
3. Use u128 in the `to_num` function
4. the lowest reward would be 2.8% * total_issuance
5. extra reward due to low effective staking ratio
Fix #617
> [GPoS] Use mainnet rules

- cstrml/market/src/lib.rs
- cstrml/market/src/mock.rs
- cstrml/market/src/tests.rs
- cstrml/swork/benchmarking/src/lib.rs
- cstrml/swork/src/lib.rs
- cstrml/swork/src/mock.rs
- cstrml/swork/src/tests.rs
- primitives/src/constants.rs
- Pending file mechanism
- New replica storage power ratio function
> [Market] Pending file mechanism
