cstrml/staking/src/lib.rs
cstrml/staking/src/tests.rs

resolves #62 
1. `phragmen_*` -> `topdown_*`;
2. change *nominators'* voting strategy(equalization including candidates);
1. `stake_limit` should always be updated every `new_era`;
2. #59 ;
3. #55 ;

[GPoS] VS topdown election algorithm

---

cstrml/staking/src/lib.rs
cstrml/staking/src/migration.rs
cstrml/staking/src/mock.rs
cstrml/staking/src/tests.rs

resolves #71 , including:
- Guarantor can `update`(new strategy), `delete` and `new` an validator;
- Add new storage `GuaranteeRelationship` which represents the `edge weights`;
- Change storage `Validations` by adding `guarantors` in it, which `sequence` represents priority(FILO);

[GPoS] Fix guarantee

---

cstrml/staking/src/lib.rs
cstrml/staking/src/mock.rs
cstrml/staking/src/tests.rs
cstrml/tee/src/lib.rs
cstrml/tee/src/mock.rs
cstrml/tee/src/tests.rs
primitives/src/constants.rs
src/chain_spec.rs

- resolves #83 
- divided `meaningful workload` and `empty worklaod`

[MPoW] Avoid double mining

---

Cargo.lock
cstrml/market/Cargo.toml
cstrml/market/src/lib.rs
cstrml/market/src/mock.rs
cstrml/market/src/tests.rs
cstrml/staking/Cargo.toml
cstrml/staking/src/inflation.rs
cstrml/staking/src/lib.rs
cstrml/staking/src/mock.rs
cstrml/staking/src/slashing.rs
cstrml/staking/src/tests.rs
cstrml/tee/Cargo.toml
cstrml/tee/src/lib.rs
cstrml/tee/src/mock.rs
node/Cargo.toml
node/build.rs
node/src/chain_spec.rs
node/src/command.rs
node/src/main.rs
node/src/service.rs
primitives/Cargo.toml
runtime/Cargo.toml
runtime/src/lib.rs

upgrade alpha.6

---

cstrml/tee/src/lib.rs
cstrml/tee/src/tests.rs

[MPoW] Check public key is unique

---

cstrml/staking/src/lib.rs
cstrml/staking/src/mock.rs
cstrml/staking/src/tests.rs

Fix #95
Guarantor increasing his votes won't bring side-effect.
- Questions
- What will happen when several guarantors  guarantee concurrently.
- Guarantor can attack the blockchain by calling `guarantee` millions of times. Each time he just increases his vote with a minimal staking.
Fix #118

New guarantee mechanism

---

cstrml/market/src/lib.rs
cstrml/market/src/tests.rs
cstrml/tee/src/lib.rs
cstrml/tee/src/mock.rs
cstrml/tee/src/tests.rs

need to calcute the piece of each transfer. Since expired_on will be changed, the information of the duration has been lost.

[Market] add completed_on in storage order for delay payment and fix a potential bug

---

cstrml/market/src/lib.rs
cstrml/market/src/tests.rs
cstrml/payment/src/tests.rs

[Market] Add mortgage mechanism for provider 

---

Cargo.lock
cstrml/staking/src/lib.rs
cstrml/staking/src/slashing.rs
cstrml/staking/src/tests.rs
runtime/Cargo.toml
runtime/src/lib.rs

Fix #134 
- Compared to the init version, slashing module doesn't change much only except for this [PR](https://github.com/paritytech/substrate/pull/5964) which is used for substrate's new weight mechanism. So I didn't modify this one.
- Slashing is based on `Stakers` and `Exposure`, which we didn't change before. So actually it works well.
- Tests about slashing are running just like they were in the substrate.

[GPoS] Enable Slashing for Staking Module

---

Cargo.lock
cstrml/market/src/mock.rs
cstrml/payment/src/mock.rs
cstrml/staking/src/mock.rs
cstrml/tee/Cargo.toml
cstrml/tee/src/api.rs
cstrml/tee/src/lib.rs
cstrml/tee/src/mock.rs
cstrml/tee/src/tests.rs
node/src/chain_spec.rs
primitives/src/lib.rs

1. Add IAS root CA
2. New identity
- IAS temp CA
- IAS signature
- ISV body
- Chain account id
- Identity sig
3. Validation process
- base64 decode IAS signature
- Extract IAS temp pub key
- Parse ISV body
- Extract `public_key` from `isvEnclaveQuoteBody` and decoded by base64([368, 431] bytes)
- 🔑  Verify certification trusted chain
- 🔑  Verify ISV body using IAS signature and IAS temp CA
- 🔑  Verify enclave code
- 🔑  Verify identity sig using `public_key`

[MPoW] New TEE register

---

cstrml/market/src/lib.rs
cstrml/market/src/mock.rs
cstrml/market/src/tests.rs
cstrml/payment/src/lib.rs
cstrml/payment/src/mock.rs
cstrml/payment/src/tests.rs
cstrml/tee/src/api.rs
cstrml/tee/src/lib.rs
cstrml/tee/src/mock.rs
runtime/src/lib.rs

1. Add `storage_price` into provider's register;
2. Remove amount when place an sorder;
3. Change `duration` from 'block_number' into `minutes(10 blocks)`;
4. Simply rename `PledgeLedger` to `Pledge`;
5. Set 2 rules:
- Minimum storage price now is 40 pico/megabytes/minute;
- Minimum duration is around 30 minutes(300 blocks);

[Market] Change Sorder price into provider side

---

cstrml/market/src/lib.rs
cstrml/market/src/mock.rs
cstrml/market/src/tests.rs
cstrml/payment/src/lib.rs
cstrml/payment/src/tests.rs
cstrml/tee/src/lib.rs
cstrml/tee/src/mock.rs

Fix #138 Fix #155 Fix #186 
- Add `fn close_sorder` in market Module<T>
- Add `fn close_sorder` in Payment Interface to related payment
- Add `fn close_sorder` in MarketInterface
- In update_identites, `close_sorder` would be invoked if the sorder is overdue.
- Full punishment will invoke `close_sorder`

[Market] Add virtual closed status for storage order

---

cstrml/market/src/lib.rs
cstrml/market/src/tests.rs
cstrml/payment/src/lib.rs
cstrml/staking/src/lib.rs
cstrml/tee/src/lib.rs
cstrml/tee/src/mock.rs
cstrml/tee/src/tests.rs

- Fix outdated sorder not close
- Change deprecated interface `remove_item`(warning under `rustc 1.46.0`)

[Market] Fix outdated sorder not close

---

docker/build.sh
docker/build_bin.sh
docker/crust-env/Dockerfile
docker/utils.sh

logging function should be colorful on macos.
use the relative path to find utils.sh
fix a typo in env dockerfile
Signed-off-by: pangwa <pangwa@gmail.com>

[Dockerize] Fix build script format show wrong under MacOS

---

cstrml/staking/src/lib.rs
cstrml/staking/src/mock.rs
cstrml/staking/src/tests.rs
runtime/src/lib.rs

SPowerRatio(storage power ratio) is a key value inside Crust Network, we may divided into 2 phases for calculating this value:
- 1st phase: mapping just 1 terabytes into fixed currency(Maxwell <this PR> is `80_000`, Olympus may will be `30`)
- 2nd phase: using formula shows in the economy whitepaper with `R/R'` stuff
1. Add `SPowerRatio`;
2. Change `stake_limit_of`;
3. Break tests with compatible with new `stake_limit_of` func;

[GPoS] Change stake limit calculation strategy

---

cstrml/tee/src/lib.rs

According to https://substrate.dev/docs/en/knowledgebase/runtime/fees#operational-dispatches, making these two extrinsics operational can give highest priority.

[MPoW] make report works be operational

---

cstrml/staking/src/lib.rs
cstrml/staking/src/mock.rs
cstrml/staking/src/tests.rs
runtime/src/lib.rs

Fix #253 
Still include era stakers clipped to avoid potential attack. Some one can create several accounts(A,B,C,D...) to be garantors. Each garantor would just garantee a small number of CRU to one validator(X). Then this validator X cannot be guranteed anymore, which doesn't make sense.

[GPoS] support MaxGuarantorRewardedPerValidator

---

cstrml/market/src/lib.rs
cstrml/payment/src/lib.rs
cstrml/staking/src/lib.rs
cstrml/swork/src/lib.rs

Fix #235
**Log Levels**
`all`: enable all log level.
`trace`: Lowest. General trace log.
`debug`: Used for debug.
`info`: Normal message.
`warn`: Something might be abnormal.
`error`: Something might be wrong.
`fatal`: Something is wrong.
`off`: off the log.
Default level should be `info`. We use `info` to prompt the message that user might have interests. `debug` is used for abnormal path. `trace` is used for normal path.

Add log and debug for runtimes

---

cstrml/swork/src/lib.rs
cstrml/swork/src/tests.rs

[MPoW] Preserve IdBonds even if pub key list is empty

---

Cargo.lock
Cargo.toml
cstrml/market/src/mock.rs
cstrml/market_v2/Cargo.toml
cstrml/market_v2/src/lib.rs
cstrml/market_v2/src/mock.rs
cstrml/market_v2/src/tests.rs
cstrml/staking/src/mock.rs
cstrml/swork/Cargo.toml
cstrml/swork/src/benchmarking.rs
cstrml/swork/src/lib.rs
cstrml/swork/src/mock.rs
cstrml/swork/src/tests.rs
cstrml/swork/src/utils.rs
primitives/src/lib.rs
primitives/src/traits.rs
runtime/Cargo.toml
runtime/src/lib.rs

Biiiiiiggest pr since repo created ☄️
Resolved #286
Resolved #287 
Resolved #288
Resolved #289 
Resolved #290  
Resolved #291  
Here is the spec details
> New DSM2.0 change including MPoW，DSM and Payment modules，The key features including: **MPoW Group，DSM I, II class files，Payment pool，Payouts update**。
```rust
pub struct WorkReport {
/// Timing judgement
pub report_slot: u64,
/// Real storage information
pub used: u64, // Real file(mapping with dsm::Files) size
pub free: u64, // Srd size
/// Assist judgement
pub reported_files_size: u64, // Reported files size
pub reported_srd_root: MerkleRoot, // Srd hash root
pub reported_files_root: MerkleRoot, // Reported files hash root
}
```
```rust
Map<SworkerPubKey, Option<PKInfo>> // is bonded?
```
```rust
struct PKInfo {
code: SworkerCode, …
```

New DSM Mechanism

---

cstrml/swork/src/lib.rs
cstrml/swork/src/tests.rs

Fix #355. An account can be group owner without reporting work.

[MPoW] An account can be group owner without identity information right now

---

cstrml/staking/src/lib.rs

Guarantor's unbond should check if `guarantee.total < ledger.active`, otherwise unbond should failed.

Fix guarantor unbond

---

cstrml/candy/src/lib.rs
cstrml/market/src/benchmarking.rs
cstrml/market/src/lib.rs
cstrml/market/src/tests.rs
cstrml/market/src/weight.rs

Storage Migration
1. MerchantLedger
2. transfer pledge_pot's money to collateral_pot
```
// "modl" ++ "crmarket" ++ "pled" is 16 bytes
T::ModuleId::get().into_sub_account("pled") 
```

[DSM] Rename pledge to  collateral

---

cstrml/market/src/lib.rs

Fix #537 
Now, it would throw out the dispatch error

[Market] Throw out the error instead of using expect to handle it

---

.github/workflows/rust.yml
cstrml/claims/src/lib.rs
cstrml/claims/src/tests.rs
cstrml/staking/src/tests.rs

1. MainNet miner is the only miner can mint erc20 locked cru info on chain, set by `sudo`;
2. 1 MainNet account can **only claim 1 type** of locked CRU;

[Claims] Add MainNet locked CRU claims

---

Cargo.lock
Cargo.toml
cstrml/candy/Cargo.toml
cstrml/claims/Cargo.toml
cstrml/csm-locking/Cargo.toml
cstrml/csm-locking/src/lib.rs
cstrml/csm-locking/src/mock.rs
cstrml/csm-locking/src/tests.rs
cstrml/csm-locking/src/weight.rs
cstrml/market/Cargo.toml
cstrml/market/src/lib.rs
cstrml/market/src/mock.rs
cstrml/market/src/tests.rs
cstrml/staking/Cargo.toml
cstrml/staking/src/lib.rs
cstrml/staking/src/tests.rs
cstrml/staking/src/weight.rs
cstrml/swork/Cargo.toml
cstrml/swork/benchmarking/Cargo.toml
cstrml/swork/benchmarking/src/mock.rs
cstrml/swork/src/mock.rs
node/Cargo.toml
node/src/chain_spec.rs
primitives/Cargo.toml
rpc/Cargo.toml
runtime/Cargo.toml
runtime/src/lib.rs

* Prepping v0.12.0 (#567)
Co-authored-by: MyronFanQiu <49134743+MyronFanQiu@users.noreply.github.com>
* [Market] Switch to storage and support change base fee online (#569)
* [Market] Switch to storage and support change base fee online
* Refine comment
* [GPoS] Support rebond extrinsic (#577)
* [GPoS] Support rebond functionality
* format
* format
* format
* [Market] Refine squencial of split money (#565)
Co-authored-by: Kun <zikunvan@gmail.com>
* [Runtime] Add CSM module (#583)
[Runtime] Add CSM Module
* [CSM] Support locking CSM (#584)
* [CSM] Support locking CSM
* Refine space
* refine comments
* refine space
* Renmae
* refine comments
fix
fix runtime
* remove migration and bump version to 23
* fix error caused by cherry-pic
Co-authored-by: Kun <zikunvan@gmail.com>

Maxwell 23 (#600)

---

cstrml/staking/src/lib.rs
cstrml/staking/src/mock.rs
cstrml/staking/src/tests.rs
runtime/src/lib.rs

If era's length is 6 hours, max validators would be 3600. 5000 is useless.

[GPoS] Dynamic Authoring and Staking Reward Ratio
